### ISSUE TITLE
Coordinates type after the last online step

### ISSUE THREAD

**Issue by jyzhuu** [yoterel/STORM-Net#11]
Hi, 
I'm now getting all the steps done but have some questions regarding the different types of coordinates we get. There are two different types and I assume the default one is the coordinates in the subject space and the other one is in the MNI space. But what is not clear here is whether the latter one is the position on the scalp or is already projected to the brain surface. I assumed it is the former and tried to project these optodes and channels to the brain surface using spm_fnirs but the results turned out to be all zeros. So I'm approaching to you to see whether it's because of my misunderstanding of the coordinates type or there is something wrong when I was running the other programs. 
Thank you!!

**Comment by yoterel** [comment]
Currently, it only transforms the points to the average MNI scalp locations, it does not project to brain surface (though the code does support projecting to brain if you need, see [here ](https://github.com/yoterel/STORM-Net/blob/eaa20befccadaa09464bcf4381dc6efa65d87352/CapCalibrator/geometry.py#L503) and [here](https://github.com/yoterel/STORM-Net/blob/eaa20befccadaa09464bcf4381dc6efa65d87352/CapCalibrator/MNI.py#L245)), you can just change:

`otherH, _, _, _, transforms = MNI.project ...`

into

`_, otherH, _, _, transforms = MNI.project ...`

However, since you are using spm_fnirs, I suggest you deselect the option to use MNI in STORM, and use the results in spm_fnirs to do the full MNI space transformation (the result from STORM will just be in the coordinate space that the input was given in).

please reopen the issue if you need any further support
