### ISSUE TITLE
Capture of optodes on the side of the head

### ISSUE THREAD

**Issue by rakhileela** [yoterel/STORM-Net#13]
In the instructions, the video is captured from the front to the back of the participant's head. However, I am working with fNIRS optodes positioned on the side of the head. I want to confirm whether the front-to-back video will accurately capture the positions of these side optodes, or if there’s a risk that they might not be registered properly. 

Is there a specific angle or approach to take with the video to ensure accurate registration for the side optodes?

**Comment by yoterel** [comment]
Since the method is based on a static template (which should be provided by you), it doesn't really matter where the optodes are (with some caveat, read until the end).
In other words, the method attempts to estimate a rigid transform of the current cap from the video, relative to its "canonical" (well-positioned) location when captured in a template (=localizing the locations of optodes + stickers on a mannequin wearing the cap). It does this by observing the so called "markers" or "stickers" which are required to be placed on the cap. This means that if the optodes were captured to a sufficient accuracy on the template, then this accuracy will more or less transfer to the estimation of their location when using this method, hence the placements of the optodes doesn't matter as much. However, if the cap violates this rigidity assumption then some error will be introduced to optodes far away from the stickers.

note: the template I am referring to is the template as defined by the preprint and the README, not to be confused with the more common term "template" used in this field for describing an atlas or MRI scan for cross-subject info, etc.

For this method to work you must take a video as instructed (front to top, or top to front and invert the video).
